version: '3.9'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: church_admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: /code/runserver.sh
    volumes:
      - .:/code
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data: