# Generated by Django 4.0.6 on 2022-10-08 21:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(default=datetime.date.today)),
                ('attendance_type', models.CharField(choices=[('SUNDAY SERVICE', 'SUNDAY SERVICE'), ('FRIDAY SERVICE', 'FRIDAY SERVICE')], default='SUNDAY SERVICE', max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=1000)),
                ('profession', models.CharField(max_length=1000)),
                ('mobile_number', models.CharField(max_length=32)),
                ('member_status', models.CharField(choices=[('VISITOR', 'VISITOR'), ('NEW CONVERT', 'NEW CONVERT'), ('FULL MEMBER', 'FULL MEMBER')], default='VISITOR', max_length=15)),
                ('photo_width', models.PositiveIntegerField(blank=True, null=True)),
                ('photo_height', models.PositiveIntegerField(blank=True, null=True)),
                ('member_photo', models.ImageField(blank=True, height_field='photo_height', max_length=2000, null=True, upload_to='photos/', width_field='photo_width')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='members.churchmember')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.churchmember')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.attendanceregister')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateTimeField(verbose_name=models.DateTimeField(blank=True, default=datetime.datetime.now))),
                ('follow_up_notes', models.CharField(blank=True, max_length=2000, null=True)),
                ('church_member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='members.churchmember')),
                ('undertaken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
