# Generated by Django 4.0.6 on 2022-11-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberattendance',
            old_name='present',
            new_name='is_present',
        ),
        migrations.AlterField(
            model_name='memberattendance',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_items', to='members.attendanceregister'),
        ),
    ]
