# Generated by Django 4.0.6 on 2022-12-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_attendanceregister_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceregister',
            name='is_already_synched',
            field=models.BooleanField(default=False),
        ),
    ]
