# Generated by Django 4.0.6 on 2022-12-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_attendanceregister_is_already_synched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceregister',
            name='is_already_synched',
            field=models.BooleanField(blank=True, default=False, editable=False, null=True),
        ),
    ]
