# Generated by Django 4.0.6 on 2022-12-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_churchmember_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupevent',
            name='follow_up_notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
